 BoxLayout
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            text: "input"
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: "Up"
            Button:
                text: "down"
    BoxLayout:
        orientation: 'vertical'
        Button:
            text: "Convert miles to km"
        Label:
            text: "answer"